[package]
name = "test_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
blake3 = "1.5.5"
hex = "0.4.3"
sha2 = { version = "0.10.8", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
