[package]
name = "sha2_hasher_risc0_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
sha2 = { version = "0.10.8", default-features = false }
core = { path="../../core" }